---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1-dev-infra
  namespace: gitops-demo
spec:
  interval: 5m0s
  path: ./app1/platdev/infra
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: x-deployments-repo
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: gitops-demo
  targetNamespace: gitops-demo
